### ISSUE TITLE
mdadm_conf not defined

### ISSUE THREAD

**Issue by louwrentius** [mrlesmithjr/ansible-mdadm#13]
Hello,

This is the configuration I've used based on the example from the readme.md. 

```
    mdadm_arrays:
      - name: 'md0'
    devices:
      - '/dev/sdb'
      - '/dev/sdc'
      - '/dev/sdd'
    level: '0'
    mountpoint: '/mnt/md0'
    state: 'present'   
```
This results in an error:

```
TASK [ansible-mdadm : arrays | Ensure {{ mdadm_conf }} file exists] **********************************************************************************************************************************************************************************************
Sunday 28 July 2019  17:58:57 +0200 (0:00:00.030)       0:00:07.929 *********** 
fatal: [nl-t1-kvm01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'mdadm_conf' is undefined\n\nThe error appears to be in '/Users/nan03/projects/genesis/roles/ansible-mdadm/tasks/arrays.yml': line 115, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: arrays | Ensure {{ mdadm_conf }} file exists\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

This error is easily resolved by adding a variable like this:

```mdadm_conf: '/etc/mdadm/mdadm.conf'```

I would suggest that this variable needs a default or must be defined mandatory as part of the usage instruction, whatever you think is best.

**Comment by mrlesmithjr** [comment]
@louwrentius Thanks for reporting this. `mdadm_conf` is set as a fact in `debian.yml` and `el.yml`. I personally have not experienced this issue and not sure if others have as well. Can you provide a bit more info (distro, etc.)? Also, whether or not the applicable task that sets this fact based on your distro is skipped by chance? Then I can dig in and see if I can duplicate the issue you experienced as well.

**Comment by mrlesmithjr** [comment]
@louwrentius Is the formatting correct for the config you posted? If so, then you definitely have a formatting issue which could be part of the issue. I just ran a quick test with bionic64 w/out any issue.

Your formatting should be like:
```yaml
mdadm_arrays:
  - name: 'md0'
    devices:
      - '/dev/sdb'
      - '/dev/sdc'
      - '/dev/sdd'
    level: '0'
    mountpoint: '/mnt/md0'
    state: 'present'
```

**Comment by mrlesmithjr** [comment]
Also just tested with CentOS 7 w/out any issues.

**Comment by louwrentius** [comment]
I think I found my fuckup:

```inventory/dev/t1/group_vars/all/vars.yml:ansible_os_family: Ubuntu```

Sorry for the inconvenience.

**Comment by mrlesmithjr** [comment]
no worries at all man.
