### ISSUE TITLE
Tries to create a default array if a host has no `mdadm_array` variable defined

### ISSUE THREAD

**Issue by Aethylred** [mrlesmithjr/ansible-mdadm#24]
**Describe the bug**
When you have a host in a group that has *no* `mdadm_arrays` variable set, the role tries to create a default array.

**To Reproduce**
1. Add a host to an inventory that does not have `/dev/sda` & `/dev/sdb`
2. Do not define `mdadm_arrays` variable
3. run a playbook that `include_role`  or depends on the role

**Expected behavior**
I expect the playbook to do nothing if `mdadm_arrays` is not defined.

**Screenshots**
```
TASK [mrlesmithjr.mdadm : arrays | Creating Array(s)] *************************************************
failed: [no_raid.test] (item={'name': 'md0', 'devices': ['/dev/sdb', '/dev/sdc'], 'filesystem': 'ext4', 'level': '1', 'mountpoint': '/mnt/md0', 'state': 'present', 'opts': 'noatime'}) => {"ansible_loop_var": "item", "changed": true, "cmd": "yes | mdadm --create /dev/md0 --level=1 --raid-devices=2 /dev/sdb /dev/sdc", "delta": "0:00:00.003582", "end": "2022-05-05 23:20:30.929538", "item": {"devices": ["/dev/sdb", "/dev/sdc"], "filesystem": "ext4", "level": "1", "mountpoint": "/mnt/md0", "name": "md0", "opts": "noatime", "state": "present"}, "msg": "non-zero return code", "rc": 2, "start": "2022-05-05 23:20:30.925956", "stderr": "mdadm: cannot open /dev/sdb: No such file or directory", "stderr_lines": ["mdadm: cannot open /dev/sdb: No such file or directory"], "stdout": "", "stdout_lines": []}
```

**Desktop (please complete the following information):**
 - OS: Rocky 8.5

**Comment by mrlesmithjr** [comment]
@markgoddard any chance you might be able to look into this? If not, no worries.

**Comment by mrlesmithjr** [comment]
Thank you for this @markgoddard
