### ISSUE TITLE
Differences in Centos/RHEL  not correctly implimented.

### ISSUE THREAD

**Issue by BatBrain** [mrlesmithjr/ansible-mdadm#26]
**Description**
Multiple issues with differences between Debian and Fedora based systems. The biggest problems being the initramfs updates and the config file location.

**To Reproduce**
1. Attempt to use on Centos or other Fedora based OS

**Expected behaviour**
Script creates `/etc/mdadm/` directory, then also creates the config file at `/etc/mdadm/mdadm.conf` this location is only valid on debian based systems, as such the raid will not be correctly assembled at boot.
The `update-initramfs` command is only valid in Debian based systems, Centos, RHEL, and Fedora all use `dracut` to manage their initramfs images and versioning.

It is not recommended to update the initramfs in the most common use-cases, namely when the OS is not installed on the RAID. This is actually detrimental if the raid becomes degraded, is absent at boot, or the boot drive is encrypted.

DNF is not being called as the package manager for the systems that use it.

**Desktop:**
 - OS: CentOS 7
 - Version: 3.10.0-1160.76.1.el7.x86_64

**Comment by mrlesmithjr** [comment]
@markgoddard - Do you have any insight into this by chance?

**Comment by markgoddard** [comment]
What I can say is that we use this role on CentOS 7 & 8, and have generally not had problems with it AFAIK.

I think there may be something odd going on here - perhaps @BatBrain used an old version of the role, or something strange in the environment caused it not to be recognised as CentOS. The role uses `ansible_facts.os_family` for this purpose.

If you look at the `tasks/el.yml` file, you can see it's using `yum` to install packages, and setting `dracut -f` as the command to update the ramdisk, and setting `/etc/mdadm.conf` as the config file.

As for updating the ramdisk, that may be true, but it seems like a separate issue. Perhaps you could raise another, with more detail on the issue?
