### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by rooterkyberian** [mrlesmithjr/ansible-mdadm#37]
Is there any chance that current version gets released any time soon?

I'm using Ansible galaxy for managing dependencies, and it seem last release accessible thru there was from 2 years ago https://galaxy.ansible.com/ui/standalone/roles/mrlesmithjr/mdadm/ .

P.S. Thank you for your (and contributors) hard work

**Comment by mrlesmithjr** [comment]
@rooterkyberian - Thanks for pointing this out. A new version is now available on Galaxy.
